name: Email on Label Added

on:
  issues:
    types: [labeled]

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send email if specific label is applied
        if: ${{ github.event.label.name == 'Status: Ready for Testing' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ vars.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Issue labeled: Status: Ready for Testing"
          to: ${{ vars.EMAIL_TO }}
          from: "GitHub Alerts <${{ secrets.EMAIL_USERNAME }}>"
          body: |
            A "Ready for Testing" label was added to an issue.

            Repo: ${{ github.repository }}
            Issue: ${{ github.event.issue.title }}
            URL: ${{ github.event.issue.html_url }}
